on:
  push:
    tags:
      - v*
  workflow_dispatch:

name: publish
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: prep/go.mod
      - name: go install nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.35.3
      - name: load version from file
        run: echo "VERSION=$(cat VERSION)" >> "$GITHUB_ENV"
      - name: make all
        run: |
          make all VERSION=$VERSION ARCH=amd64
          make all VERSION=$VERSION ARCH=arm64
      - name: publish
        working-directory: dist
        run: |
          ls | xargs -n1 -I '{}' \
            curl -F package=@{} https://${{ secrets.GEMFURY_TOKEN }}@push.fury.io/iio/
